---
title: <small>An introduction to digital open <br>research in clinical psychology</small>
author: <small>Matthias Weiler</small>
date: <small>18.03.2019</small>
output:
  revealjs::revealjs_presentation:
    theme: black
    center: TRUE
    self_contained: FALSE
    incremental: TRUE
    reveal_plugins: ["chalkboard"]
    reveal_options:
      chalkboard: 
      readonly: FALSE
---

# <small> What did we do last session?</small>

----

We talked about your <br>
personal open science projects

----

... your hopes

----

... and your fears

----

Any questions or anything to add?



# <small>Last session's homework</small>

----

Who of you prepared a  
presentation for today?

----

Who of you uploaded this  
presentation to GitHub?

----

Any questions regarding  
last session's homework?



# <small>Today:<br>Present and review your research proposals</small>



# <small>Basic rules for your presentation</small>

----

You only have 3 minutes <br>
for your presentation

----

You will be notified before  
the final minute starts

----

You have 1 additional minute  
to answer questions

----

Any questions?



# <small>Proposal reviews</small>

----

Choose your favorite projects  
(one from each university)

----

The two projects from each  
university with the most votes  
will "win" (final projects)

----

Any questions?



# <small>Research groups</small>

----

Research will be done in mixed groups  
(with students from each university)

----

If your project was not chosen  
as a final project, you will work  
in somebody else's project

----

Any questions?



# <small>Running order</small>

----

01: Ismini  
02: Grigoria  
03: Androniki  
04: Maria-Eirini N.  
05: Marios  

----

06: Sotiria  
07: Maria B.  
08: Georgia  
09: Konstantinos  
10: Ariadni  

----

11: Aggeliki  
12: Thomas  
13: Dimitra  
14: Maria Ko.  
15: Anna  

----

16: Fotini  
17: Maria-Dialechti Ke.  



# <small>Let's go</small>

----

01: Ismini  
(next: Grigoria)  

----

02: Grigoria  
(next: Androniki)  

----

03: Androniki  
(next: Maria-Eirini N.)  

----

04: Maria-Eirini N.	 
(next: Marios)  

----

05: Marios  
(next: Sotiria)  

----

06: Sotiria  
(next: Maria B.)  

----

07: Maria B.  
(next: Georgia)  

----

08: Georgia  
(next: Konstantinos)  

----

09: Konstantinos  
(next: Ariadni)  

----

10: Ariadni  
(next: Aggeliki)  

----

11: Aggeliki  
(next: Thomas)  

----

12: Thomas  
(next: Dimitra)  

----

13: Dimitra  
(next: Maria Ko.)  

----

14: Maria Ko.  
(next: Anna)  

----

15: Anna  
(next: Fotini)  

----

16: Fotini  
(next: Maria-Dialechti Ke.)  

----

17: Maria-Dialechti Ke.  

----

Great job everyone!



# <small>Choose the final projects</small>

----

Choose your favorite projects  
(one from each university)

----

Post your choices in the  
\# choose-final-projects  
channel in Slack



# <small>Choose your research group</small>

----

Post the names of the research groups  
in the # choose-research-group Slack  
channel in your order of preference  
(favorite 1., 2., 3., 4. least favorite)



# <small>Preview: next session</small>

----

On Friday, 29th of March

----

"Data collection"

----

No course on Monday!



# <small>Homework</small>

----

Apply the suggested  
changes from the review

----

Add your research project to  
the "Research projects" section  
of the course in the OSF

----

Register your research project in  
the OSF using the Preregistration  
Template from AsPredicted.org 

----

Connect your GitHub repository to  
your research project in the OSF



# <small>Any questions?</small>



# <small>Thank you for your attention</small>
